apiVersion: v1
kind: Pod
metadata:
  name: pod-hw
  labels:
    app: pod-hw
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
    - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: service-hw
spec:
  selector:
    app: pod-hw
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
